const didYouKnow = [
  'The first Nextflow commit was made in 2013',
  'nf-core has more than 1000 modules currently available',
  'nf-core has more than 90 different pipelines',
  'The Nextflow channels podcast has a new episode every 2 weeks',
  'The first nf-core pipeline was nf-core/methylseq (April, 2018)',
  'fastqc was the first nf-core module (July, 2019)',
  'The first Nextflow Git commit took place on a Friday, March, 22, 2013.',
  'Nextflow has had 249 official releases',
  'The favorite week day for Nextflow developers to commit is Monday',
  '23.6% of all Nextflow commits happened on weekends',
  'The Nextflow repo has over 450.000 lines',
  'Beatriz Martin San Juan was the second person to ever commit in the Nextflow repository (2013)',
  'Cedric Champeau was the third person to ever commit in the Nextflow repository (2014)',
  'Rob Syme committed to the repository in 2014. Who would guess he would join Seqera in 2022?',
  'The Nextflow Slack workspace has 2.923 members',
  'The nf-core GitHub organization has over 800 members with over 2200 contributors over the years!',
  'There are more than 100 repositories in the nf-core GitHub organization',
  'There are over 39000 commits in the repositories within the nf-core GitHub organization',
  'The nf-core/methylseq pipeline has bene cloned over 11000 times',
  'The nf-core/rnaseq pipeline was the second nf-core pipeline ever',
  'The nf-core/rnaseq pipeline has been cloned over 86000 times',
  'The nf-core pipelines repositories have received over half a million unique visitors through the years',
  'Our benchmarks show that Fusion is 2x faster and 3x cheaper than default S3',
  'There are free monthly online group demos of Seqera Platform',
  'Seqera has a quarterly email newsletter with community news and updates',
  'Tower Pro is free for academics',
  'Over 100k pipelines have been launched on Tower',
  'Regular community talks and online events in the last 12 months have resulted in over 3,000 YouTube subscribers',
  'Regular community talks and online events in the last 12 months have resulted in over 170k YouTube views',
  'Training recordings from the past 12 months on YouTube have resulted already in over 20k views',
];

export default didYouKnow;
